#!/bin/sh

if [ $# -ne 1 ]; then
	echo "Usage: $0 LOGFILE" 1>&2
	exit 1
fi

log=$1
for f in $(seq 0 10 100); do
  printf "%3d " ${f}
  n=$(grep -E " ${f}$" ${log} | wc -l)
  for i in $(seq ${n}); do
    echo -n '*'
  done
  echo
done
